"use client";

import { Download, Printer } from "lucide-react";

/**
 * Statement actions: "PDF İndir" opens the browser's print dialog in a mode
 * that saves as PDF (Chrome/Edge: "Save as PDF" destination pre-hinted via
 * the document title), plus a plain "Yazdır" for physical printing.
 * No server round-trip — the PDF is generated by the browser at full fidelity.
 */
export function PrintButton({ customerName, period }: { customerName?: string; period?: string }) {
  function downloadPdf() {
    // Set a descriptive filename hint: browsers use <title> as the default PDF name.
    const original = document.title;
    if (customerName && period) {
      document.title = `Ekstre - ${customerName} - ${period}`;
    }
    window.print();
    // Restore after the dialog closes (print is synchronous-ish in Chrome).
    setTimeout(() => {
      document.title = original;
    }, 500);
  }

  return (
    <div className="flex items-center gap-2 no-print">
      <button
        onClick={downloadPdf}
        className="inline-flex items-center gap-2 rounded bg-navy-800 text-white text-sm font-medium px-4 py-2 hover:bg-navy-700 transition-colors"
      >
        <Download size={15} />
        PDF İndir
      </button>
      <button
        onClick={() => window.print()}
        className="inline-flex items-center gap-2 rounded border border-line bg-white text-sm font-medium px-4 py-2 text-ink hover:bg-gold-100/60 transition-colors"
      >
        <Printer size={15} />
        Yazdır
      </button>
    </div>
  );
}
